### ISSUE TITLE
User functionality

### ISSUE THREAD

**Issue by twp88** [nikeshashar/tutorialreport#11]
As the PO 
So that we can controller user functionality
I would like to have user authentication

**Comment by nikeshashar** [comment]
Do you mean user sign in? Do we want to control / store user data? Perhaps allow for Google OAuth & Github OAuth out of the box so we don't have to handle usernames?

**Comment by twp88** [comment]
Basically I was thinking that a user can't write a review unless they're signed in. I think we should do Google OAuth & Github OAuth, but usernames are made pretty simple with devise (it just uses user email).

**Comment by nikeshashar** [comment]
Cool. I gotta make sure we remain GDPR compliant from the start if we're to roll out. Basically we'll need some form of access control in that case as we're storing identifiable data on people.

**Comment by twp88** [comment]
So I've been having a look at some GDPR stuff and I see what you mean. It looks like a bit a pain. That being said, having skimmed through some stuff, I think our only data points that would fall under the new law would be the users name and email. 
I've been thinking about this over the past couple of days. Google OAuth & Github OAuth would be the quick and easy way out, BUT I think if this were to be rolled out in the future it would hurt us to only have these two options. 
On the one hand there are those who (unbelievably) don't have an account with either of those two services. On the other hand there are those (like myself on occasion) who have preferred to create a first person account with a service as opposed to continuing to provide google with yet more data about my browsing habits. 
I guess I feel like asking for someones name and email isn't asking for much. We could even just change it to just an email address.

**Comment by twp88** [comment]
The other thing that might enter into the equation is the storage of user comments, and the ease of access/deletion/editing of those comments if a user so wishes. I think we're going to have a look at this GDPR issue in greater detail.

**Comment by twp88** [comment]
For the moment I will crack on with adding Devise to the project for this ticket, with the full knowledge that it might have to change (as with anything) in the future.
